// This file is auto-generated by process_dataset.py. Do not edit directly.

const SKIN_DATABASE = [
  {
    "id": 1,
    "gender": "male",
    "frontImage": "extracted/1/front.jpg",
    "rightImage": "extracted/1/right-side.jpg",
    "leftImage": "extracted/1/left-side.jpg",
    "skinType": "Balanced / Normal",
    "undertone": "Warm Olive",
    "fitzpatrick": "Type IV",
    "story": "Your skin has a beautiful warm olive undertone (Fitzpatrick Type IV) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed active breakouts on the skin surface, though the deeper lipid barrier retains baseline strength. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Balanced / Normal profile:** Balanced lipid-moisture base, with active breakout clusters present.",
      "**Hormonal breakouts concentrated along the chin & jawline:** Concentrated red papules indicating hormonal cycles or stress. ",
      "**Under-eye area:** Pigmentation-type dark circles (melanin deposition/shadowing). Mild puffiness noticed. Fine lines detected.",
      "**Forehead congestion:** Pronounced micro-bumps. Humidity-induced micro-bumps (closed comedones)."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi 10% Vitamin C Serum",
          "benefit": "brightens under-eye shadows, stimulates density, and boosts facial glow"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Booster 5% Niacinamide Glycolic Serum",
          "benefit": "gently exfoliates forehead micro-bumps (closed comedones) and smooths rough skin"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 32,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 68,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 48,
          "y": 26,
          "concern": "T-Zone Congestion",
          "desc": "Forehead textured bumps"
        },
        {
          "x": 48,
          "y": 48,
          "concern": "Pore Shine",
          "desc": "Active sebum zone"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  },
  {
    "id": 2,
    "gender": "female",
    "frontImage": "extracted/2/front.jpg",
    "rightImage": "extracted/2/right-side.jpg",
    "leftImage": "extracted/2/left-side.jpg",
    "skinType": "Balanced / Normal",
    "undertone": "Neutral",
    "fitzpatrick": "Type IV",
    "story": "Your skin has a beautiful neutral undertone (Fitzpatrick Type IV) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed active breakouts on the skin surface, though the deeper lipid barrier retains baseline strength. There are signs of surface sensitivity and vascular reactivity on your cheeks. Your skin is showing dehydration\u2014meaning it has active surface shine but is lacking essential hydration in deeper layers. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Balanced / Normal profile:** Balanced lipid-moisture base, with active breakout clusters present.",
      "**Reactive Skin Barrier:** Surface redness and high sensitivity on the cheeks, responsive to soothing botanicals.",
      "**Dehydration detected:** High surface shine paired with underlying texture roughness, indicating a lack of crucial water content.",
      "**Hormonal breakouts concentrated along the chin & jawline:** Concentrated red papules indicating hormonal cycles or stress. ",
      "**Refined under-eyes:** Strong skin density and even melanin levels under the eyes.",
      "**Forehead congestion:** Pronounced micro-bumps. Humidity-induced micro-bumps (closed comedones)."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Booster 5% Niacinamide Glycolic Serum",
          "benefit": "gently exfoliates forehead micro-bumps (closed comedones) and smooths rough skin"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 48,
          "y": 26,
          "concern": "T-Zone Congestion",
          "desc": "Forehead textured bumps"
        },
        {
          "x": 48,
          "y": 48,
          "concern": "Pore Shine",
          "desc": "Active sebum zone"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  },
  {
    "id": 3,
    "gender": "female",
    "frontImage": "extracted/3/front.jpg",
    "rightImage": "extracted/3/right-side.jpg",
    "leftImage": "extracted/3/left-side.jpg",
    "skinType": "Balanced / Normal",
    "undertone": "Warm Olive",
    "fitzpatrick": "Type IV",
    "story": "Your skin has a beautiful warm olive undertone (Fitzpatrick Type IV) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed active breakouts on the skin surface, though the deeper lipid barrier retains baseline strength. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Balanced / Normal profile:** Balanced lipid-moisture base, with active breakout clusters present.",
      "**Hormonal breakouts concentrated along the chin & jawline:** Concentrated red papules indicating hormonal cycles or stress. Indicators of deep cystic acne present.",
      "**Under-eye area:** Pigmentation-type dark circles (melanin deposition/shadowing). Mild puffiness noticed. Fine lines detected.",
      "**Forehead congestion:** Pronounced micro-bumps. Humidity-induced micro-bumps (closed comedones)."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi 10% Vitamin C Serum",
          "benefit": "brightens under-eye shadows, stimulates density, and boosts facial glow"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Booster 5% Niacinamide Glycolic Serum",
          "benefit": "gently exfoliates forehead micro-bumps (closed comedones) and smooths rough skin"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 32,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 68,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 48,
          "y": 26,
          "concern": "T-Zone Congestion",
          "desc": "Forehead textured bumps"
        },
        {
          "x": 48,
          "y": 48,
          "concern": "Pore Shine",
          "desc": "Active sebum zone"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  },
  {
    "id": 4,
    "gender": "female",
    "frontImage": "extracted/4/front.jpg",
    "rightImage": "extracted/4/right-side.jpg",
    "leftImage": "extracted/4/left-side.jpg",
    "skinType": "Oily",
    "undertone": "Warm Golden",
    "fitzpatrick": "Type IV",
    "story": "Your skin has a beautiful warm golden undertone (Fitzpatrick Type IV) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed an active sebum cycle across your T-zone and cheeks, creating shine and wider pore appearance. There are signs of surface sensitivity and vascular reactivity on your cheeks. Your skin is showing dehydration\u2014meaning it has active surface shine but is lacking essential hydration in deeper layers. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Oily profile:** Highly active sebum gland activity across all facial zones. Enlarged Pores (Active Sebum)",
      "**Reactive Skin Barrier:** Surface redness and high sensitivity on the cheeks, responsive to soothing botanicals.",
      "**Dehydration detected:** High surface shine paired with underlying texture roughness, indicating a lack of crucial water content.",
      "**Hormonal breakouts concentrated along the chin & jawline:** Concentrated red papules indicating hormonal cycles or stress. Indicators of deep cystic acne present.",
      "**Under-eye area:** Pigmentation-type dark circles (melanin deposition/shadowing). Mild puffiness noticed. Fine lines detected.",
      "**Forehead congestion:** Pronounced micro-bumps. Humidity-induced micro-bumps (closed comedones)."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi 10% Vitamin C Serum",
          "benefit": "brightens under-eye shadows, stimulates density, and boosts facial glow"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Booster 5% Niacinamide Glycolic Serum",
          "benefit": "gently exfoliates forehead micro-bumps (closed comedones) and smooths rough skin"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 32,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 68,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 48,
          "y": 26,
          "concern": "T-Zone Congestion",
          "desc": "Forehead textured bumps"
        },
        {
          "x": 48,
          "y": 48,
          "concern": "Pore Shine",
          "desc": "Active sebum zone"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  },
  {
    "id": 5,
    "gender": "male",
    "frontImage": "extracted/5/front.jpg",
    "rightImage": "extracted/5/right-side.jpg",
    "leftImage": "extracted/5/left-side.jpg",
    "skinType": "Combination (Oily T-Zone)",
    "undertone": "Cool Ashy",
    "fitzpatrick": "Type IV",
    "story": "Your skin has a beautiful cool ashy undertone (Fitzpatrick Type IV) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed a responsive lipid barrier that builds natural shine through the T-zone alongside active blemish spots on the cheeks. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Combination (Oily T-Zone) profile:** Radiant surface displaying shine on forehead/nose with active blemish spots visible on cheeks. ",
      "**Moderate active breakouts:** Notable areas of active inflammation (Post-Acne Marks (PIH / PIE)) on cheeks and chin.",
      "**Under-eye area:** Pigmentation-type dark circles (melanin deposition/shadowing). Mild puffiness noticed. Fine lines detected.",
      "**Forehead congestion:** Pronounced micro-bumps. Humidity-induced micro-bumps (closed comedones)."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi 10% Vitamin C Serum",
          "benefit": "brightens under-eye shadows, stimulates density, and boosts facial glow"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Booster 5% Niacinamide Glycolic Serum",
          "benefit": "gently exfoliates forehead micro-bumps (closed comedones) and smooths rough skin"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 32,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 68,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 48,
          "y": 26,
          "concern": "T-Zone Congestion",
          "desc": "Forehead textured bumps"
        },
        {
          "x": 48,
          "y": 48,
          "concern": "Pore Shine",
          "desc": "Active sebum zone"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  },
  {
    "id": 6,
    "gender": "female",
    "frontImage": "extracted/6/front.jpg",
    "rightImage": "extracted/6/right-side.jpg",
    "leftImage": "extracted/6/left-side.jpg",
    "skinType": "Balanced / Normal",
    "undertone": "Warm Golden",
    "fitzpatrick": "Type IV",
    "story": "Your skin has a beautiful warm golden undertone (Fitzpatrick Type IV) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed active breakouts on the skin surface, though the deeper lipid barrier retains baseline strength. There are signs of surface sensitivity and vascular reactivity on your cheeks. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Balanced / Normal profile:** Balanced lipid-moisture base, with active breakout clusters present.",
      "**Reactive Skin Barrier:** Surface redness and high sensitivity on the cheeks, responsive to soothing botanicals.",
      "**Moderate active breakouts:** Notable areas of active inflammation (Active Inflammatory Acne) on cheeks and chin.",
      "**Under-eye area:** Pigmentation-type dark circles (melanin deposition/shadowing). Mild puffiness noticed. Fine lines detected.",
      "**Forehead congestion:** Pronounced micro-bumps. Humidity-induced micro-bumps (closed comedones)."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi 10% Vitamin C Serum",
          "benefit": "brightens under-eye shadows, stimulates density, and boosts facial glow"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Booster 5% Niacinamide Glycolic Serum",
          "benefit": "gently exfoliates forehead micro-bumps (closed comedones) and smooths rough skin"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 32,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 68,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 48,
          "y": 26,
          "concern": "T-Zone Congestion",
          "desc": "Forehead textured bumps"
        },
        {
          "x": 48,
          "y": 48,
          "concern": "Pore Shine",
          "desc": "Active sebum zone"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  },
  {
    "id": 7,
    "gender": "male",
    "frontImage": "extracted/7/front.jpg",
    "rightImage": "extracted/7/right-side.jpg",
    "leftImage": "extracted/7/left-side.jpg",
    "skinType": "Combination (Oily T-Zone)",
    "undertone": "Warm Golden",
    "fitzpatrick": "Type IV",
    "story": "Your skin has a beautiful warm golden undertone (Fitzpatrick Type IV) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed a responsive lipid barrier that builds natural shine through the T-zone alongside active blemish spots on the cheeks. There are signs of surface sensitivity and vascular reactivity on your cheeks. Your skin is showing dehydration\u2014meaning it has active surface shine but is lacking essential hydration in deeper layers. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Combination (Oily T-Zone) profile:** Radiant surface displaying shine on forehead/nose with active blemish spots visible on cheeks. Visible Pores on Cheeks",
      "**Reactive Skin Barrier:** Surface redness and high sensitivity on the cheeks, responsive to soothing botanicals.",
      "**Dehydration detected:** High surface shine paired with underlying texture roughness, indicating a lack of crucial water content.",
      "**Hormonal breakouts concentrated along the chin & jawline:** Concentrated red papules indicating hormonal cycles or stress. ",
      "**Under-eye area:** Vascular-type dark circles (thin skin displaying micro-vessels). Mild puffiness noticed. Fine lines detected.",
      "**Forehead congestion:** Pronounced micro-bumps. Humidity-induced micro-bumps (closed comedones)."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi 10% Vitamin C Serum",
          "benefit": "brightens under-eye shadows, stimulates density, and boosts facial glow"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Booster 5% Niacinamide Glycolic Serum",
          "benefit": "gently exfoliates forehead micro-bumps (closed comedones) and smooths rough skin"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 32,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 68,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 48,
          "y": 26,
          "concern": "T-Zone Congestion",
          "desc": "Forehead textured bumps"
        },
        {
          "x": 48,
          "y": 48,
          "concern": "Pore Shine",
          "desc": "Active sebum zone"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  },
  {
    "id": 8,
    "gender": "female",
    "frontImage": "extracted/8/front.jpg",
    "rightImage": "extracted/8/right-side.jpg",
    "leftImage": "extracted/8/left-side.jpg",
    "skinType": "Oily",
    "undertone": "Cool Ashy",
    "fitzpatrick": "Type IV",
    "story": "Your skin has a beautiful cool ashy undertone (Fitzpatrick Type IV) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed an active sebum cycle across your T-zone and cheeks, creating shine and wider pore appearance. Your skin is showing dehydration\u2014meaning it has active surface shine but is lacking essential hydration in deeper layers. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Oily profile:** Highly active sebum gland activity across all facial zones. Enlarged Pores (Active Sebum)",
      "**Dehydration detected:** High surface shine paired with underlying texture roughness, indicating a lack of crucial water content.",
      "**Moderate active breakouts:** Notable areas of active inflammation (Post-Acne Marks (PIH / PIE)) on cheeks and chin.",
      "**Refined under-eyes:** Strong skin density and even melanin levels under the eyes.",
      "**Forehead congestion:** Pronounced micro-bumps. Humidity-induced micro-bumps (closed comedones)."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Booster 5% Niacinamide Glycolic Serum",
          "benefit": "gently exfoliates forehead micro-bumps (closed comedones) and smooths rough skin"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 48,
          "y": 26,
          "concern": "T-Zone Congestion",
          "desc": "Forehead textured bumps"
        },
        {
          "x": 48,
          "y": 48,
          "concern": "Pore Shine",
          "desc": "Active sebum zone"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  },
  {
    "id": 9,
    "gender": "female",
    "frontImage": "extracted/9/front.jpg",
    "rightImage": "extracted/9/right-side.jpg",
    "leftImage": "extracted/9/left-side.jpg",
    "skinType": "Combination (Oily T-Zone)",
    "undertone": "Warm Golden",
    "fitzpatrick": "Type V",
    "story": "Your skin has a beautiful warm golden undertone (Fitzpatrick Type V) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed a responsive lipid barrier that builds natural shine through the T-zone alongside active blemish spots on the cheeks. There are signs of surface sensitivity and vascular reactivity on your cheeks. Your skin is showing dehydration\u2014meaning it has active surface shine but is lacking essential hydration in deeper layers. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Combination (Oily T-Zone) profile:** Radiant surface displaying shine on forehead/nose with active blemish spots visible on cheeks. Visible Pores on Cheeks",
      "**Reactive Skin Barrier:** Surface redness and high sensitivity on the cheeks, responsive to soothing botanicals.",
      "**Dehydration detected:** High surface shine paired with underlying texture roughness, indicating a lack of crucial water content.",
      "**Hormonal breakouts concentrated along the chin & jawline:** Concentrated red papules indicating hormonal cycles or stress. Indicators of deep cystic acne present.",
      "**Under-eye area:** Vascular-type dark circles (thin skin displaying micro-vessels). Mild puffiness noticed. Fine lines detected.",
      "**Forehead congestion:** Pronounced micro-bumps. Humidity-induced micro-bumps (closed comedones)."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi 10% Vitamin C Serum",
          "benefit": "brightens under-eye shadows, stimulates density, and boosts facial glow"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Booster 5% Niacinamide Glycolic Serum",
          "benefit": "gently exfoliates forehead micro-bumps (closed comedones) and smooths rough skin"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 32,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 68,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 48,
          "y": 26,
          "concern": "T-Zone Congestion",
          "desc": "Forehead textured bumps"
        },
        {
          "x": 48,
          "y": 48,
          "concern": "Pore Shine",
          "desc": "Active sebum zone"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  },
  {
    "id": 10,
    "gender": "female",
    "frontImage": "extracted/10/front.jpg",
    "rightImage": "extracted/10/right-side.jpg",
    "leftImage": "extracted/10/left-side.jpg",
    "skinType": "Combination (Oily T-Zone)",
    "undertone": "Neutral",
    "fitzpatrick": "Type IV",
    "story": "Your skin has a beautiful neutral undertone (Fitzpatrick Type IV) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed a responsive lipid barrier that builds natural shine through the T-zone alongside active blemish spots on the cheeks. Your skin is showing dehydration\u2014meaning it has active surface shine but is lacking essential hydration in deeper layers. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Combination (Oily T-Zone) profile:** Radiant surface displaying shine on forehead/nose with active blemish spots visible on cheeks. Visible Pores on Cheeks",
      "**Dehydration detected:** High surface shine paired with underlying texture roughness, indicating a lack of crucial water content.",
      "**Moderate active breakouts:** Notable areas of active inflammation (Active Inflammatory Acne) on cheeks and chin.",
      "**Under-eye area:** Pigmentation-type dark circles (melanin deposition/shadowing). Mild puffiness noticed. Fine lines detected.",
      "**Refined forehead:** Smooth forehead skin showing outstanding cell clearance."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi 10% Vitamin C Serum",
          "benefit": "brightens under-eye shadows, stimulates density, and boosts facial glow"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 32,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 68,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 48,
          "y": 26,
          "concern": "T-Zone Congestion",
          "desc": "Forehead textured bumps"
        },
        {
          "x": 48,
          "y": 48,
          "concern": "Pore Shine",
          "desc": "Active sebum zone"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  },
  {
    "id": 11,
    "gender": "female",
    "frontImage": "extracted/11/front.jpg",
    "rightImage": "extracted/11/right-side.jpg",
    "leftImage": "extracted/11/left-side.jpg",
    "skinType": "Balanced / Normal",
    "undertone": "Warm Olive",
    "fitzpatrick": "Type IV",
    "story": "Your skin has a beautiful warm olive undertone (Fitzpatrick Type IV) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed active breakouts on the skin surface, though the deeper lipid barrier retains baseline strength. Your skin is showing dehydration\u2014meaning it has active surface shine but is lacking essential hydration in deeper layers. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Balanced / Normal profile:** Balanced lipid-moisture base, with active breakout clusters present.",
      "**Dehydration detected:** High surface shine paired with underlying texture roughness, indicating a lack of crucial water content.",
      "**Hormonal breakouts concentrated along the chin & jawline:** Concentrated red papules indicating hormonal cycles or stress. ",
      "**Under-eye area:** Pigmentation-type dark circles (melanin deposition/shadowing). Mild puffiness noticed. Fine lines detected.",
      "**Mild forehead congestion:** Minor texture suggesting pores that need targeted daily exfoliation."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi 10% Vitamin C Serum",
          "benefit": "brightens under-eye shadows, stimulates density, and boosts facial glow"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Booster 5% Niacinamide Glycolic Serum",
          "benefit": "gently exfoliates forehead micro-bumps (closed comedones) and smooths rough skin"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 32,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 68,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  },
  {
    "id": 12,
    "gender": "female",
    "frontImage": "extracted/12/front.jpg",
    "rightImage": "extracted/12/right-side.jpg",
    "leftImage": "extracted/12/left-side.jpg",
    "skinType": "Balanced / Normal",
    "undertone": "Warm Golden",
    "fitzpatrick": "Type IV",
    "story": "Your skin has a beautiful warm golden undertone (Fitzpatrick Type IV) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed active breakouts on the skin surface, though the deeper lipid barrier retains baseline strength. There are signs of surface sensitivity and vascular reactivity on your cheeks. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Balanced / Normal profile:** Balanced lipid-moisture base, with active breakout clusters present.",
      "**Reactive Skin Barrier:** Surface redness and high sensitivity on the cheeks, responsive to soothing botanicals.",
      "**Hormonal breakouts concentrated along the chin & jawline:** Concentrated red papules indicating hormonal cycles or stress. Indicators of deep cystic acne present.",
      "**Under-eye area:** Vascular-type dark circles (thin skin displaying micro-vessels). Mild puffiness noticed. Fine lines detected.",
      "**Forehead congestion:** Pronounced micro-bumps. Humidity-induced micro-bumps (closed comedones)."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi 10% Vitamin C Serum",
          "benefit": "brightens under-eye shadows, stimulates density, and boosts facial glow"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Booster 5% Niacinamide Glycolic Serum",
          "benefit": "gently exfoliates forehead micro-bumps (closed comedones) and smooths rough skin"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 32,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 68,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 48,
          "y": 26,
          "concern": "T-Zone Congestion",
          "desc": "Forehead textured bumps"
        },
        {
          "x": 48,
          "y": 48,
          "concern": "Pore Shine",
          "desc": "Active sebum zone"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  },
  {
    "id": 13,
    "gender": "female",
    "frontImage": "extracted/13/front.jpg",
    "rightImage": "extracted/13/right-side.jpg",
    "leftImage": "extracted/13/left-side.jpg",
    "skinType": "Balanced / Normal",
    "undertone": "Warm Golden",
    "fitzpatrick": "Type III",
    "story": "Your skin has a beautiful warm golden undertone (Fitzpatrick Type III) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed active breakouts on the skin surface, though the deeper lipid barrier retains baseline strength. There are signs of surface sensitivity and vascular reactivity on your cheeks. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Balanced / Normal profile:** Balanced lipid-moisture base, with active breakout clusters present.",
      "**Reactive Skin Barrier:** Surface redness and high sensitivity on the cheeks, responsive to soothing botanicals.",
      "**Hormonal breakouts concentrated along the chin & jawline:** Concentrated red papules indicating hormonal cycles or stress. Indicators of deep cystic acne present.",
      "**Under-eye area:** Pigmentation-type dark circles (melanin deposition/shadowing).  Fine lines detected.",
      "**Forehead congestion:** Pronounced micro-bumps. Humidity-induced micro-bumps (closed comedones)."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi 10% Vitamin C Serum",
          "benefit": "brightens under-eye shadows, stimulates density, and boosts facial glow"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Booster 5% Niacinamide Glycolic Serum",
          "benefit": "gently exfoliates forehead micro-bumps (closed comedones) and smooths rough skin"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 32,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 68,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 48,
          "y": 26,
          "concern": "T-Zone Congestion",
          "desc": "Forehead textured bumps"
        },
        {
          "x": 48,
          "y": 48,
          "concern": "Pore Shine",
          "desc": "Active sebum zone"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  },
  {
    "id": 14,
    "gender": "female",
    "frontImage": "extracted/14/front.jpg",
    "rightImage": "extracted/14/right-side.jpg",
    "leftImage": "extracted/14/left-side.jpg",
    "skinType": "Oily",
    "undertone": "Cool Ashy",
    "fitzpatrick": "Type IV",
    "story": "Your skin has a beautiful cool ashy undertone (Fitzpatrick Type IV) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed an active sebum cycle across your T-zone and cheeks, creating shine and wider pore appearance. Your skin is showing dehydration\u2014meaning it has active surface shine but is lacking essential hydration in deeper layers. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Oily profile:** Highly active sebum gland activity across all facial zones. Enlarged Pores (Active Sebum)",
      "**Dehydration detected:** High surface shine paired with underlying texture roughness, indicating a lack of crucial water content.",
      "**Moderate active breakouts:** Notable areas of active inflammation (Active Inflammatory Acne) on cheeks and chin.",
      "**Under-eye area:** Pigmentation-type dark circles (melanin deposition/shadowing). Mild puffiness noticed. Fine lines detected.",
      "**Forehead congestion:** Pronounced micro-bumps. Humidity-induced micro-bumps (closed comedones)."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi 10% Vitamin C Serum",
          "benefit": "brightens under-eye shadows, stimulates density, and boosts facial glow"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Booster 5% Niacinamide Glycolic Serum",
          "benefit": "gently exfoliates forehead micro-bumps (closed comedones) and smooths rough skin"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 32,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 68,
          "y": 55,
          "concern": "Under-Eye Shadow",
          "desc": "Concentrated dark circles"
        },
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 48,
          "y": 26,
          "concern": "T-Zone Congestion",
          "desc": "Forehead textured bumps"
        },
        {
          "x": 48,
          "y": 48,
          "concern": "Pore Shine",
          "desc": "Active sebum zone"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  },
  {
    "id": 15,
    "gender": "male",
    "frontImage": "extracted/15/front.jpg",
    "rightImage": "extracted/15/right-side.jpg",
    "leftImage": "extracted/15/left-side.jpg",
    "skinType": "Balanced / Normal",
    "undertone": "Cool Ashy",
    "fitzpatrick": "Type IV",
    "story": "Your skin has a beautiful cool ashy undertone (Fitzpatrick Type IV) that is absolutely gorgeous\u2014and it is working hard to protect you right now! We noticed active breakouts on the skin surface, though the deeper lipid barrier retains baseline strength. Remember, your skin is reacting, not failing, and we are going to deliver specific active botanicals to clear breakouts, balance sebum, and fade any dark marks.",
    "noticed": [
      "**Balanced / Normal profile:** Balanced lipid-moisture base, with active breakout clusters present.",
      "**Moderate active breakouts:** Notable areas of active inflammation (Post-Acne Marks (PIH / PIE)) on cheeks and chin.",
      "**Refined under-eyes:** Strong skin density and even melanin levels under the eyes.",
      "**Refined forehead:** Smooth forehead skin showing outstanding cell clearance."
    ],
    "ritual": {
      "morning": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "sweeps overnight sebum, purifies pores, and clears micro-bumps"
        },
        {
          "product": "Kishmi Repair & Glow 10% Niacinamide Serum",
          "benefit": "minimizes enlarged pores, balances sebum, and fades dark post-acne marks (PIH)"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "weightless barrier-repair gel that deeply hydrates without feeding acne-causing bacteria"
        },
        {
          "product": "Kishmi Mineral Shield SPF 50+ Sunscreen",
          "benefit": "creates a physical shield (Zinc/Titanium) to prevent UV rays from deepening dark spots or post-acne scars"
        }
      ],
      "night": [
        {
          "product": "Kishmi PureGlow Clarifying Face Wash",
          "benefit": "washes daily sweat, environmental dust, and sweeps clogged pores"
        },
        {
          "product": "Kishmi Oil Control 2% Salicylic Face Serum",
          "benefit": "penetrates deep to clear active blemish clusters, calm redness, and reduce swelling"
        },
        {
          "product": "Kishmi Skin Revival For 30+ 0.2% Retinol Cream",
          "benefit": "nighttime cellular renewal booster to smooth fine lines, firm texture, and fade stubborn marks"
        },
        {
          "product": "Kishmi Simply Hydrating Niacinamide 3% Moisturizer",
          "benefit": "locks in moisture overnight and repairs the lipid skin barrier during cellular rest"
        },
        {
          "product": "Kishmi Lip Glow Nourishing Balm",
          "benefit": "seals lips overnight with beeswax and shea butter to prevent hydration escape"
        }
      ]
    },
    "tips": [
      "Swap heavy moisturizing creams for light, hydrating gel-based formulations in hot and humid climates to avoid sweat-induced congestion.",
      "Apply physical sunscreen indoors too; Indian UV levels trigger pigment cells even through standard glass windows.",
      "Wash pillowcases twice a week to avoid re-introducing hair oils and sweat bacteria to active skin zones."
    ],
    "dermWarning": "If your breakouts feel deep, painful under the skin, or if barrier redness causes burning, a friendly dermatologist can provide specialized clinical support.",
    "markers": {
      "front": [
        {
          "x": 42,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 58,
          "y": 66,
          "concern": "Active Breakout",
          "desc": "Red chin papules"
        },
        {
          "x": 28,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        },
        {
          "x": 72,
          "y": 60,
          "concern": "Active Breakout",
          "desc": "Cheek inflammatory breakout"
        }
      ],
      "left": [
        {
          "x": 48,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ],
      "right": [
        {
          "x": 52,
          "y": 68,
          "concern": "Active Breakout",
          "desc": "Jawline post-acne mark"
        }
      ]
    }
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = SKIN_DATABASE;
}
